### ISSUE TITLE
Generic methods

### ISSUE THREAD

**Issue by bannmann** [tomokinakamaru/silverchain#39]
I'm struggling to properly express generic methods in the `.ag` file. The Java signature of the action class methods should end up like this:

```
<T> void addPlugin(Class<T> targetType, Plugin<? super T> plugin)
```

Judging from the examples and the grammar definition, I'd guess that Silverchain does not yet support type parameters on methods, but only on classes.

Please add support for this to the `.ag` syntax.

Note: the Java tutorial chapter ["Generic Methods"](https://docs.oracle.com/javase/tutorial/extra/generics/methods.html) lists a few other variants that should be supported as well. (Just ignore the non-void return type.)

```
public boolean containsAll(Collection<?> c);
public boolean addAll(Collection<? extends E> c);
public static <T> void copy(List<T> dest, List<? extends T> src)
```

Of particular interest is the simple `SomeType<?>` which I'd need as well - while the raw type works fine, I'd like to avoid suppressing the associated warning in my action class.

**Comment by tomokinakamaru** [comment]
I thought about this for a moment, and found that it contains two problems:
1. Missing wildcard support
2. Missing support for method-level type parameters

I think it's possible to support both, but I am not sure if it is. To be honest, I do not exactly remember why I chose not to support them since I designed this a long time ago :( So let me think again and do some experimental implementation. I will post a comment here when I find if it's possible or not. If you have any ideas on them (e.g. expected syntax in AG files), I would appreciate to hear them.

---

Background:
At the time of starting this project, I was thinking of creating a fluent API generator that can generate a library in multiple languages from a single AG file. This is probably why I chose not to support (1) and (2). Since those features are not ones that every language has, supporting them would limit the output languages of Silverchain.
However, I changed my mind while thinking about the issues you posted (this issue and #38). It would benefit the users to develop a fluent API generator focusing on _Java_ libraries, more than sticking on the multi-language support.

**Comment by bannmann** [comment]
> It would benefit the users to develop a fluent API generator focusing on _Java_ libraries, more than sticking on the multi-language support.

I wholeheartedly agree. Not because I'm a Java developer, but because in my experience, trying to make a solution cross-platform, cross-language or even cross-usecase very often results in any combination of severe limitations, vastly increased development efforts or not ending up being used in the other scenario (platform/language/usecase).

---

Regarding the syntax, here is an (admittedly radical) outside-the-box-thinking idea: If Silverchain is (now) focused on Java, is there really still a good reason to keep the custom syntax? Both you and the Silverchain users are familiar with Java syntax, especially generics, so why should you have to invent, maintain and extend a custom syntax that the users would have to translate their desired Java syntax into? 

The reason I can think of is that a custom syntax might be easier to parse. Then again, there might be grammars for Java available. Also, you don't need the entirety of the JLS, only the parts about one method signature. And if concatenating method signatures *with spaces* turns out to be ambiguous (e.g. void vs non-void), one could instead use something like `+` (or a unicode char like "➞"), or require wrapping each signature in square braces.

**Comment by tomokinakamaru** [comment]
Thank you for the helpful comments.

I have implemented the support for wildcards and method-level type parameters in the branch fix/issue39. I tested them with the input at [listutil.ag](https://github.com/tomokinakamaru/silverchain/blob/fix/issue39/src/test/resources/listutil.ag). If this fix is fine for your case, I will merge the branch into `master`.

There are now three kinds of type parameters:
1. Ones listed in a type declaration
    1. Ones listed before `;` or without `;`
        These type parameters are shared in a chain expression and are included in the generated type declaration. For example, if you give an input like `Foo[T]: …`, Silverchain generates `Foo<T>`.
    2. Ones listed after `;`
        These type parameters are shared in a chain expression but are **not** included in the generated type declaration. For example, If you give an input like `Foo[;T]`, Silverchain generates `Foo` (without the type parameter). The examples [mapbuilder.ag](https://github.com/tomokinakamaru/silverchain/blob/master/src/test/resources/mapbuilder.ag) and  [listutil.ag](https://github.com/tomokinakamaru/silverchain/blob/fix/issue39/src/test/resources/listutil.ag) are their usecases.
2. Ones listed in a method declaration (New)
These type parameters are **not** shared in a chain expression. They are only used in the method.

---

Making AG syntax more like Java is a great idea, but I didn't apply it this time since it seems a different topic. I will do it later (as soon as possible) together with the following:
- Add the support for `import` statements
- Remove the `--language` option

**Comment by bannmann** [comment]
I tested the branch build with my project; the method type parameters work perfectly. Thanks a lot! Looking forward to the master merge and the resulting docker image. 😃

---

For reference, these are the variants I used:
```
addPlugin[T](Class[T] targetType, Plugin[? :> T] plugin)

foo(Class[?] type, String bar)
```
