### ISSUE TITLE
Valid parameter name is rejected

### ISSUE THREAD

**Issue by bannmann** [tomokinakamaru/silverchain#45]
When one of the methods of an `.ag` chain rule uses the parameter name `name1`, Silverchain fails with the following message:
```
Encountered " <NUMBER> "1 "" at line 219, column 16.
Was expecting:
    ")" ...
```

Please make sure that any parameter name which is valid for Java is accepted by Silverchain, as well.

**Comment by tomokinakamaru** [comment]
Thanks for the report!

This problem has been fixed in the branch `fix/issue43`. However, the branch includes the syntax changes as listed in https://github.com/tomokinakamaru/silverchain/issues/43#issue-929790678.

If all the syntax changes are fine for you, I will merge the corresponding PR #44 (I can merge it immediately). If not, I will create another branch and pickup the changes on parameter names (but this takes a little while). Which would you like?

**Comment by bannmann** [comment]
It's fine to fix this together with the changed syntax, thanks!
